---
abstract: 'Puts the build files in the project root'
author:
  - 'Keedi Kim - 김도형 <keedi@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-PathInRoot
requires:
  Dist::Zilla: 5.006
  Moose: 0
  Path::Tiny: 0
  namespace::autoclean: 0
resources:
  bugtracker: https://github.com/keedi/Dist-Zilla-Plugin-PathInRoot/issues
  homepage: https://github.com/keedi/Dist-Zilla-Plugin-PathInRoot
  repository: https://github.com/keedi/Dist-Zilla-Plugin-PathInRoot.git
version: 0.001
